linkerd/linkerd2-proxy-api

Makefile, rs/src/arbitrary.rs
The rust package includes a special 'arbitrary' feature flag to support
quickcheck integration. This feature flag was not tested via `make rs`.
Commit 1a82147 created an `http_types` module that was not imported in
the `arbitrary` module.
This change adds the `--all-features` flag to cargo for `make rs` and
fixes compilation.
=> Fix rust compilation for 'arbitrary' feature

rs/Cargo.toml, rs/src/arbitrary.rs, rs/src/lib.rs
This is in service of an attempt to have the proxy depend only on a
single version of `rand` (linkerd/linkerd2-proxy#170); `quickcheck` 0.6
depends on a much older `rand` than most of our other dependencies.
Signed-off-by: Eliza Weisman <eliza@buoyant.io>
=> Bump `quickcheck` dependency to 0.8.0

.gitignore, Cargo.lock, Makefile
Currently, CI tests my pick up newer, incompatible dependency versions.
=> Store a Cargo.lock to preserve test dependencies

CHANGES.md, Cargo.lock, rs/Cargo.toml
* Add headers and trailers to Tap events
* Update tower-grpc to 0.1 from crates.io
Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>
=> Update for v0.1.10

Cargo.lock, rs/Cargo.toml, rs/src/arbitrary.rs, rs/src/lib.rs
This requires upgrading quickcheck as well.
Also adopt 2018 idioms, apply rustfmt, etc.
=> rust: Update rand to 0.7

Makefile
`make go` invokes `go get -u ...` on protoc-gen-go, which causes it to
be upgraded in CI, causing CI to fail when a newer version is available.
This change removes the `-u` flag to prevent updating to a newer version
than is vendored.
=> go: Do not upgrade protoc-gen-go on `make`

Makefile, rs/Cargo.toml
When debugging generated code, it's useful to enable rustfmt so that
it's legible. This change makes this a feature flag.
The makefile is updated to avoid requiring rustfmt with `make rs` which
is used in CI.
=> rust: Add a rustfmt feature flag

rs/src/lib.rs
There is no `TryFrom` implementation from `net.TcpAddress` to
`SocketAddr`,  though we've manually implemented it in api-resovle
crate.
This change provides a generalized implementation. It also modifies
existing IP converters to be on the address type directly and not a
reference (since IP addrs are generally consisered copyable).
=> rust: Add a SocketAddr converter

Cargo.lock, rs/Cargo.toml
Tonic was recently updated to v0.3. This commit updates the `proxy-api`
crate's Tonic dependency so we can continue following patches.
The breaking change doesn't effect this crate. It shouldn't effect the
proxy's use of this crate, either, since it's to a method that's only
used when using Tonic's `transport` feature (which the proxy does not
use). See: https://github.com/hyperium/tonic/blob/master/CHANGELOG.md#breaking-changes
Signed-off-by: Eliza Weisman <eliza@buoyant.io>
=> rs: update Tonic to 0.3

.github/workflows/ci.yml, Cargo.lock, rs/Cargo.toml
This branch updates the `tonic` dependency to a Git dep on a branch that
uses Tokio 0.3 and the latest versions of other dependencies, such as
`bytes` and `tower`. This is necessary for linkerd/linkerd2-proxy#732.
Hopefully a new `tonic` release will be out soon and we can change the
git dependency back to a crates.io dependency...
Signed-off-by: Eliza Weisman <eliza@buoyant.io>
=> rust: update tonic dep to tokio 0.3

CHANGES.md, Cargo.lock, rs/Cargo.toml
This branch updates the Rust proxy-api crate's dependencies
to use `prost` 0.7 and a branch of `tonic` that uses Tokio 1.0
and `tower` 0.4. When the `tonic` changes merge, we should
point that dep at master, and then at crates.io when the next
`tonic` version is released.
I also updated the `rand` dependency to try and reduce the
number of `rand`s in the proxy's dep tree.
Signed-off-by: Eliza Weisman <eliza@buoyant.io>
=> update dependencies to Tokio 1.0

.github/workflows/ci.yml, Cargo.lock, deny.toml
This change adds cargo-deny and clippy checks to CI to
help validate the Rust crate.
=> Apply linting and auditing to the Rust crate

Cargo.lock, rs/Cargo.toml, rs/src/gen/http_types.rs, rs/src/gen/net.rs
The `thiserror` crate reduces boilplate for error types. This change
updates the `net` and `http_types` errors to use `thiserror`. This fixes
a missing error implementation for `InvalidIpNetwork`.
This change also updates some conditional depdencies to behave as
expected:
- the `http_types` module does not use `h2`--this is only needed by `tap`;
- the `client` and `server` feature shoudl imply `transport`--these
features are useless without transport bindings.
=> rust: Use thiserror for error types

.github/dependabot.yml, Cargo.lock
This change enables dependabot for Actions, Go, and Rust dependencies.
=> Configure dependabot version updates

src/gen/http_types.rs
This PR adds the missing `PATCH` variant in the http method
parsing logic. This prevents the `PATCH` method from
being marked as Unregistered in the TAP responses.
Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>
=> http: add `PATCH` variant during parsing

Cargo.toml
Cargo expects various links to be defined in published crate manifests.
This change adds homepage, repository, and documentation links.
=> Add missing Cargo metadata

.devcontainer/devcontainer.json, .github/workflows/markdown.yml, CHANGES.md, CONTRIBUTING.md, Cargo.toml, GOVERNANCE.md, LICENSE, MAINTAINERS.md, README.md
This repo is missing a README.
This change adds a general overview of the repo and adds a markdown
linter to CI.
This change updates the copyright in the LICENSE file. It also fixes
Rust crate documentation generation so that all features are enabled by
docs.rs.
Signed-off-by: Oliver Gould <ver@buoyant.io>
=> Add a README

.github/workflows/rust.yml
This helps to ensure, for instance, that tests run even when there is an
error in the generated docs.
Signed-off-by: Oliver Gould <ver@buoyant.io>
=> ci: Split rust workflow into multiple jobs

.github/workflows/rust.yml, justfile
Our Rust CI currently does not run `clippy` and `test` with
`--all-features`, so these checks are effectively being skipped today.
This change adds `--all-features` so that all rust modules are checked.
Furthermore, the `justfile` has been updated to no longer set
`RUSTFLAGS` so that rust-analyzer, etc can use the same cached object
files without rebuilding. The `RUSTFLAGS` configuration has been moved
to the GitHub workflow.
Signed-off-by: Oliver Gould <ver@buoyant.io>
=> ci: Run clippy, tests on all cargo features

.github/workflows/rust.yml, justfile
Currently, the `just rs-clippy`, etc, do not actually enable any
features. This makes it easy to misrun checks (locally). This change
adds a `features` variable--that defaults to `all`--that control which
features are enabled on rust targets.
Signed-off-by: Oliver Gould <ver@buoyant.io>
=> dev: Build all features by default

Cargo.lock, Cargo.toml, src/gen/io.linkerd.proxy.destination.rs, src/gen/io.linkerd.proxy.grpc_route.rs, src/gen/io.linkerd.proxy.http_route.rs, src/gen/io.linkerd.proxy.http_types.rs, src/gen/io.linkerd.proxy.identity.rs, src/gen/io.linkerd.proxy.inbound.rs, src/gen/io.linkerd.proxy.meta.rs, src/gen/io.linkerd.proxy.net.rs, src/gen/io.linkerd.proxy.tap.rs
This branch updates the `tonic` and `tonic-build` deps to 0.8, and the
`prost`/`prost-build` deps to 0.11. I've regenerated the protos with the
new versions.
Closes #135 
Closes #136
=> update `tonic` to 0.8, `prost` to 0.11

Cargo.lock, src/gen/io.linkerd.proxy.destination.rs, src/gen/io.linkerd.proxy.grpc_route.rs, src/gen/io.linkerd.proxy.http_route.rs, src/gen/io.linkerd.proxy.identity.rs, src/gen/io.linkerd.proxy.inbound.rs, src/gen/io.linkerd.proxy.meta.rs, src/gen/io.linkerd.proxy.net.rs, src/gen/io.linkerd.proxy.tap.rs
Version 0.11.0 of `prost-build` had a (very minor) bug where an
additional character of whitespace was added in front of RustDoc
comments. Version 0.11.1 fixes that.
This branch updates to v0.11.1 and regens the protos (again).
Closes #140
=> rust: bump `prost-build` to 0.11.1, undo whitespace change

.github/workflows/release.yml
This appears to expect that the release tag is named `release/vX.Y.Z` rather than just `vX.Y.Z`, but all the existing release tags use the second naming format. This is preventing v0.8.0 from being released, as the publish action fails with
```
Error: Crate version v0.8.0 does not match tag refs/tags/v0.8.0
```
because the refs path was not removed (as it's expected to be `refs/tags/release/` rather than refs/tags/`).
I'm...not entirely sure how this ever worked previously...
=> actions: fix wrong substring match in release.yml

Cargo.lock, deny.toml
Resolves some RUSTSEC complaints. Adds a license exception for unicode.
=> rust: Update lagging dependencies

Cargo.lock
Apparently v0.3.17 is yanked, which is causing our CI build to complain at us:
https://github.com/linkerd/linkerd2-proxy-api/actions/runs/5093960127/jobs/9157185970?pr=243
This PR fixes it.
=> build(deps): update `h2` from v0.3.17 to v0.3.19

Cargo.toml
The destination API now requires the `meta` feature to be enabled.
=> fix(destination): enable the `meta` feature
